# Generated by Django 5.1.6 on 2025-02-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data_fim',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_inicio',
            field=models.DateField(auto_now_add=True),
        ),
    ]
