# Generated by Django 5.1.6 on 2025-02-14 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0002_alter_reuniao_data_fim_alter_reuniao_data_inicio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='data_fim',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='reuniao',
            name='data_inicio',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
