# Generated by Django 5.1.6 on 2025-02-18 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0004_reuniao_criado_por_reuniao_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='criado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reunioes_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
