# Generated by Django 5.1.6 on 2025-02-22 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_alter_reuniao_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reuniao',
            name='data_fim',
        ),
    ]
