# Generated by Django 5.1.6 on 2025-02-25 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0006_remove_reuniao_data_fim'),
    ]

    operations = [
        migrations.AddField(
            model_name='reuniao',
            name='motivo_rejeicao',
            field=models.TextField(blank=True, null=True),
        ),
    ]
