# Generated by Django 5.1.6 on 2025-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0007_reuniao_motivo_rejeicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reuniao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelamento_solicitado', 'Cancelamento Solicitado'), ('cancelado', 'Cancelado')], default='pendente', max_length=25),
        ),
    ]
